# Generated by Django 4.2.5 on 2023-09-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='users_like',
        ),
    ]
